import { City } from "@/types"

export const IDF_CITIES: City[] = [

  // ── PARIS (75) ──────────────────────────────────────────
  {
    name: "Paris",
    slug: "paris",
    department: "Paris",
    departmentCode: "75",
    population: 2161000,
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    name: "Paris 1er",
    slug: "paris-1er",
    department: "Paris",
    departmentCode: "75",
    population: 17000,
    lat: 48.8606,
    lng: 2.3477,
  },
  {
    name: "Paris 2ème",
    slug: "paris-2eme",
    department: "Paris",
    departmentCode: "75",
    population: 22000,
    lat: 48.8670,
    lng: 2.3499,
  },
  {
    name: "Paris 3ème",
    slug: "paris-3eme",
    department: "Paris",
    departmentCode: "75",
    population: 35000,
    lat: 48.8630,
    lng: 2.3590,
  },
  {
    name: "Paris 4ème",
    slug: "paris-4eme",
    department: "Paris",
    departmentCode: "75",
    population: 28000,
    lat: 48.8534,
    lng: 2.3566,
  },
  {
    name: "Paris 5ème",
    slug: "paris-5eme",
    department: "Paris",
    departmentCode: "75",
    population: 59000,
    lat: 48.8462,
    lng: 2.3508,
  },
  {
    name: "Paris 6ème",
    slug: "paris-6eme",
    department: "Paris",
    departmentCode: "75",
    population: 41000,
    lat: 48.8496,
    lng: 2.3331,
  },
  {
    name: "Paris 7ème",
    slug: "paris-7eme",
    department: "Paris",
    departmentCode: "75",
    population: 57000,
    lat: 48.8566,
    lng: 2.3139,
  },
  {
    name: "Paris 8ème",
    slug: "paris-8eme",
    department: "Paris",
    departmentCode: "75",
    population: 36000,
    lat: 48.8752,
    lng: 2.3084,
  },
  {
    name: "Paris 9ème",
    slug: "paris-9eme",
    department: "Paris",
    departmentCode: "75",
    population: 60000,
    lat: 48.8782,
    lng: 2.3367,
  },
  {
    name: "Paris 10ème",
    slug: "paris-10eme",
    department: "Paris",
    departmentCode: "75",
    population: 91000,
    lat: 48.8766,
    lng: 2.3590,
  },
  {
    name: "Paris 11ème",
    slug: "paris-11eme",
    department: "Paris",
    departmentCode: "75",
    population: 147000,
    lat: 48.8590,
    lng: 2.3790,
  },
  {
    name: "Paris 12ème",
    slug: "paris-12eme",
    department: "Paris",
    departmentCode: "75",
    population: 142000,
    lat: 48.8417,
    lng: 2.3887,
  },
  {
    name: "Paris 13ème",
    slug: "paris-13eme",
    department: "Paris",
    departmentCode: "75",
    population: 179000,
    lat: 48.8317,
    lng: 2.3622,
  },
  {
    name: "Paris 14ème",
    slug: "paris-14eme",
    department: "Paris",
    departmentCode: "75",
    population: 136000,
    lat: 48.8330,
    lng: 2.3270,
  },
  {
    name: "Paris 15ème",
    slug: "paris-15eme",
    department: "Paris",
    departmentCode: "75",
    population: 234000,
    lat: 48.8422,
    lng: 2.2952,
  },
  {
    name: "Paris 16ème",
    slug: "paris-16eme",
    department: "Paris",
    departmentCode: "75",
    population: 166000,
    lat: 48.8637,
    lng: 2.2769,
  },
  {
    name: "Paris 17ème",
    slug: "paris-17eme",
    department: "Paris",
    departmentCode: "75",
    population: 168000,
    lat: 48.8840,
    lng: 2.3089,
  },
  {
    name: "Paris 18ème",
    slug: "paris-18eme",
    department: "Paris",
    departmentCode: "75",
    population: 195000,
    lat: 48.8924,
    lng: 2.3444,
  },
  {
    name: "Paris 19ème",
    slug: "paris-19eme",
    department: "Paris",
    departmentCode: "75",
    population: 184000,
    lat: 48.8850,
    lng: 2.3812,
  },
  {
    name: "Paris 20ème",
    slug: "paris-20eme",
    department: "Paris",
    departmentCode: "75",
    population: 195000,
    lat: 48.8638,
    lng: 2.3969,
  },

  // ── HAUTS-DE-SEINE (92) ─────────────────────────────────
  {
    name: "Boulogne-Billancourt",
    slug: "boulogne-billancourt",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 121000,
    lat: 48.8352,
    lng: 2.2400,
  },
  {
    name: "Nanterre",
    slug: "nanterre",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 95000,
    lat: 48.8924,
    lng: 2.2069,
  },
  {
    name: "Courbevoie",
    slug: "courbevoie",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 84000,
    lat: 48.8974,
    lng: 2.2537,
  },
  {
    name: "Rueil-Malmaison",
    slug: "rueil-malmaison",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 80000,
    lat: 48.8773,
    lng: 2.1860,
  },
  {
    name: "Colombes",
    slug: "colombes",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 85000,
    lat: 48.9231,
    lng: 2.2516,
  },
  {
    name: "Asnières-sur-Seine",
    slug: "asnieres-sur-seine",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 86000,
    lat: 48.9175,
    lng: 2.2853,
  },
  {
    name: "Antony",
    slug: "antony",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 62000,
    lat: 48.7537,
    lng: 2.2980,
  },
  {
    name: "Levallois-Perret",
    slug: "levallois-perret",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 64000,
    lat: 48.8952,
    lng: 2.2872,
  },
  {
    name: "Neuilly-sur-Seine",
    slug: "neuilly-sur-seine",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 61000,
    lat: 48.8846,
    lng: 2.2693,
  },
  {
    name: "Clichy",
    slug: "clichy",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 61000,
    lat: 48.9042,
    lng: 2.3057,
  },
  {
    name: "Issy-les-Moulineaux",
    slug: "issy-les-moulineaux",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 67000,
    lat: 48.8237,
    lng: 2.2700,
  },
  {
    name: "Clamart",
    slug: "clamart",
    department: "Hauts-de-Seine",
    departmentCode: "92",
    population: 53000,
    lat: 48.8011,
    lng: 2.2630,
  },

  // ── SEINE-SAINT-DENIS (93) ───────────────────────────────
  {
    name: "Saint-Denis",
    slug: "saint-denis",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 113000,
    lat: 48.9362,
    lng: 2.3574,
  },
  {
    name: "Montreuil",
    slug: "montreuil",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 107000,
    lat: 48.8638,
    lng: 2.4483,
  },
  {
    name: "Aubervilliers",
    slug: "aubervilliers",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 84000,
    lat: 48.9143,
    lng: 2.3833,
  },
  {
    name: "Aulnay-sous-Bois",
    slug: "aulnay-sous-bois",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 84000,
    lat: 48.9397,
    lng: 2.4962,
  },
  {
    name: "Vitry-sur-Seine",
    slug: "vitry-sur-seine",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 92000,
    lat: 48.7874,
    lng: 2.3929,
  },
  {
    name: "Bobigny",
    slug: "bobigny",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 51000,
    lat: 48.9081,
    lng: 2.4406,
  },
  {
    name: "Noisy-le-Grand",
    slug: "noisy-le-grand",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 67000,
    lat: 48.8476,
    lng: 2.5519,
  },
  {
    name: "Pantin",
    slug: "pantin",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 55000,
    lat: 48.8952,
    lng: 2.4035,
  },
  {
    name: "Vincennes",
    slug: "vincennes",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 49000,
    lat: 48.8478,
    lng: 2.4390,
  },
  {
    name: "Saint-Ouen",
    slug: "saint-ouen",
    department: "Seine-Saint-Denis",
    departmentCode: "93",
    population: 50000,
    lat: 48.9128,
    lng: 2.3328,
  },

  // ── VAL-DE-MARNE (94) ───────────────────────────────────
  {
    name: "Créteil",
    slug: "creteil",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 91000,
    lat: 48.7793,
    lng: 2.4553,
  },
  {
    name: "Ivry-sur-Seine",
    slug: "ivry-sur-seine",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 60000,
    lat: 48.8132,
    lng: 2.3834,
  },
  {
    name: "Champigny-sur-Marne",
    slug: "champigny-sur-marne",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 77000,
    lat: 48.8171,
    lng: 2.5137,
  },
  {
    name: "Saint-Maur-des-Fossés",
    slug: "saint-maur-des-fosses",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 79000,
    lat: 48.7966,
    lng: 2.4878,
  },
  {
    name: "Maisons-Alfort",
    slug: "maisons-alfort",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 54000,
    lat: 48.8059,
    lng: 2.4375,
  },
  {
    name: "Villejuif",
    slug: "villejuif",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 57000,
    lat: 48.7942,
    lng: 2.3614,
  },
  {
    name: "Vincennes",
    slug: "vincennes-94",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 49000,
    lat: 48.8478,
    lng: 2.4390,
  },
  {
    name: "Fontenay-sous-Bois",
    slug: "fontenay-sous-bois",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 52000,
    lat: 48.8513,
    lng: 2.4779,
  },
  {
    name: "Alfortville",
    slug: "alfortville",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 44000,
    lat: 48.7959,
    lng: 2.4240,
  },
  {
    name: "Charenton-le-Pont",
    slug: "charenton-le-pont",
    department: "Val-de-Marne",
    departmentCode: "94",
    population: 29000,
    lat: 48.8218,
    lng: 2.4140,
  },

  // ── ESSONNE (91) ────────────────────────────────────────
  {
    name: "Évry-Courcouronnes",
    slug: "evry-courcouronnes",
    department: "Essonne",
    departmentCode: "91",
    population: 68000,
    lat: 48.6258,
    lng: 2.4281,
  },
  {
    name: "Massy",
    slug: "massy",
    department: "Essonne",
    departmentCode: "91",
    population: 47000,
    lat: 48.7253,
    lng: 2.2716,
  },
  {
    name: "Corbeil-Essonnes",
    slug: "corbeil-essonnes",
    department: "Essonne",
    departmentCode: "91",
    population: 51000,
    lat: 48.6137,
    lng: 2.4806,
  },
  {
    name: "Palaiseau",
    slug: "palaiseau",
    department: "Essonne",
    departmentCode: "91",
    population: 34000,
    lat: 48.7151,
    lng: 2.2464,
  },
  {
    name: "Sainte-Geneviève-des-Bois",
    slug: "sainte-genevieve-des-bois",
    department: "Essonne",
    departmentCode: "91",
    population: 34000,
    lat: 48.6461,
    lng: 2.3213,
  },
  {
    name: "Viry-Châtillon",
    slug: "viry-chatillon",
    department: "Essonne",
    departmentCode: "91",
    population: 31000,
    lat: 48.6703,
    lng: 2.3763,
  },
  {
    name: "Juvisy-sur-Orge",
    slug: "juvisy-sur-orge",
    department: "Essonne",
    departmentCode: "91",
    population: 15000,
    lat: 48.6889,
    lng: 2.3751,
  },
  {
    name: "Les Ulis",
    slug: "les-ulis",
    department: "Essonne",
    departmentCode: "91",
    population: 26000,
    lat: 48.6820,
    lng: 2.1660,
  },

  // ── YVELINES (78) ────────────────────────────────────────
  {
    name: "Versailles",
    slug: "versailles",
    department: "Yvelines",
    departmentCode: "78",
    population: 85000,
    lat: 48.8014,
    lng: 2.1301,
  },
  {
    name: "Saint-Germain-en-Laye",
    slug: "saint-germain-en-laye",
    department: "Yvelines",
    departmentCode: "78",
    population: 39000,
    lat: 48.8988,
    lng: 2.0940,
  },
  {
    name: "Mantes-la-Jolie",
    slug: "mantes-la-jolie",
    department: "Yvelines",
    departmentCode: "78",
    population: 44000,
    lat: 48.9893,
    lng: 1.7169,
  },
  {
    name: "Poissy",
    slug: "poissy",
    department: "Yvelines",
    departmentCode: "78",
    population: 37000,
    lat: 48.9290,
    lng: 2.0472,
  },
  {
    name: "Sartrouville",
    slug: "sartrouville",
    department: "Yvelines",
    departmentCode: "78",
    population: 52000,
    lat: 48.9376,
    lng: 2.1642,
  },
  {
    name: "Trappes",
    slug: "trappes",
    department: "Yvelines",
    departmentCode: "78",
    population: 32000,
    lat: 48.7762,
    lng: 2.0041,
  },
  {
    name: "Conflans-Sainte-Honorine",
    slug: "conflans-sainte-honorine",
    department: "Yvelines",
    departmentCode: "78",
    population: 35000,
    lat: 49.0000,
    lng: 2.0981,
  },
  {
    name: "Élancourt",
    slug: "elancourt",
    department: "Yvelines",
    departmentCode: "78",
    population: 28000,
    lat: 48.7803,
    lng: 1.9588,
  },
  {
    name: "Vélizy-Villacoublay",
    slug: "velizy-villacoublay",
    department: "Yvelines",
    departmentCode: "78",
    population: 21000,
    lat: 48.7803,
    lng: 2.1700,
  },

  // ── VAL-D'OISE (95) ─────────────────────────────────────
  {
    name: "Cergy",
    slug: "cergy",
    department: "Val-d'Oise",
    departmentCode: "95",
    population: 67000,
    lat: 49.0361,
    lng: 2.0630,
  },
  {
    name: "Argenteuil",
    slug: "argenteuil",
    department: "Val-d'Oise",
    departmentCode: "95",
    population: 110000,
    lat: 48.9472,
    lng: 2.2467,
  },
  {
    name: "Sarcelles",
    slug: "sarcelles",
    department: "Val-d'Oise",
    departmentCode: "95",
    population: 58000,
    lat: 48.9956,
    lng: 2.3805,
  },
  {
    name: "Pontoise",
    slug: "pontoise",
    department: "Val-d'Oise",
    departmentCode: "95",
    population: 30000,
    lat: 49.0499,
    lng: 2.1006,
  },
  {
    name: "Garges-lès-Gonesse",
    slug: "garges-les-gonesse",
    department: "Val-d'Oise",
    departmentCode: "95",
    population: 40000,
    lat: 48.9724,
    lng: 2.4037,
  },
  {
    name: "Enghien-les-Bains",
    slug: "enghien-les-bains",
    department: "Val-d'Oise",
    departmentCode: "95",
    population: 12000,
    lat: 48.9706,
    lng: 2.3092,
  },
  {
    name: "Goussainville",
    slug: "goussainville",
    department: "Val-d'Oise",
    departmentCode: "95",
    population: 29000,
    lat: 49.0266,
    lng: 2.4620,
  },

  // ── SEINE-ET-MARNE (77) ──────────────────────────────────
  {
    name: "Meaux",
    slug: "meaux",
    department: "Seine-et-Marne",
    departmentCode: "77",
    population: 56000,
    lat: 48.9603,
    lng: 2.8888,
  },
  {
    name: "Chelles",
    slug: "chelles",
    department: "Seine-et-Marne",
    departmentCode: "77",
    population: 54000,
    lat: 48.8786,
    lng: 2.5943,
  },
  {
    name: "Melun",
    slug: "melun",
    department: "Seine-et-Marne",
    departmentCode: "77",
    population: 41000,
    lat: 48.5404,
    lng: 2.6597,
  },
  {
    name: "Pontault-Combault",
    slug: "pontault-combault",
    department: "Seine-et-Marne",
    departmentCode: "77",
    population: 36000,
    lat: 48.7988,
    lng: 2.6063,
  },
  {
    name: "Torcy",
    slug: "torcy",
    department: "Seine-et-Marne",
    departmentCode: "77",
    population: 23000,
    lat: 48.8512,
    lng: 2.6528,
  },
  {
    name: "Dammarie-les-Lys",
    slug: "dammarie-les-lys",
    department: "Seine-et-Marne",
    departmentCode: "77",
    population: 21000,
    lat: 48.5155,
    lng: 2.6483,
  },
  {
    name: "Savigny-le-Temple",
    slug: "savigny-le-temple",
    department: "Seine-et-Marne",
    departmentCode: "77",
    population: 28000,
    lat: 48.5850,
    lng: 2.5856,
  },
  {
    name: "Lognes",
    slug: "lognes",
    department: "Seine-et-Marne",
    departmentCode: "77",
    population: 14000,
    lat: 48.8388,
    lng: 2.6261,
  },
]

// ── HELPERS ──────────────────────────────────────────────────

// Toutes les villes d'un département
export function getCitiesByDepartment(code: string): City[] {
  return IDF_CITIES.filter((c) => c.departmentCode === code)
}

// Trouver une ville par son slug
export function getCityBySlug(slug: string): City | undefined {
  return IDF_CITIES.find((c) => c.slug === slug)
}

// 3 villes proches (même département, hors elle-même)
export function getNearestCities(city: City, count = 3): City[] {
  return IDF_CITIES
    .filter(
      (c) =>
        c.departmentCode === city.departmentCode &&
        c.slug !== city.slug
    )
    .sort((a, b) => {
      const distA = Math.hypot(a.lat - city.lat, a.lng - city.lng)
      const distB = Math.hypot(b.lat - city.lat, b.lng - city.lng)
      return distA - distB
    })
    .slice(0, count)
}

// Stats globales pour les compteurs
export const IDF_STATS = {
  totalCities: IDF_CITIES.length,
  departments: 8,
  parisArrondissements: 20,
}
